[package]
name = "aws-manager"
version = "0.0.1" # https://crates.io/crates/aws-manager/versions
edition = "2021"
rust-version = "1.62"
publish = true
description = "AWS manager"
homepage = "https://github.com/gyuho/aws-manager"
license = "Apache-2.0"

[dependencies]
aws-config = "0.15.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-cloudformation = "0.15.0"
aws-sdk-cloudwatch = "0.15.0"
aws-sdk-cloudwatchlogs = "0.15.0"
aws-sdk-ec2 = "0.15.0"
aws-sdk-kms = "0.15.0"
aws-sdk-s3 = "0.15.0"
aws-sdk-sts = "0.15.0"
aws-smithy-types = "0.45.0"
aws-types = "0.15.0"
bs58 = "0.4.0"
byteorder = "1.4.3"
chrono = "0.4.19"
command-manager = "0.0.1"
compress-manager = "0.0.2" # https://crates.io/crates/compress-manager/versions
http-manager = "0.0.1"
human-readable = "0.0.1"
hyper = { version = "0.14.19", features = ["full"] }
lazy_static = "1.4.0"
log = "0.4.17"
rand = "0.8.5"
random-manager = "0.0.1" # https://crates.io/crates/random-manager/versions
ring = "0.16.20"
ripemd = "0.1.1"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.81"
sysinfo = "0.24.5"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
tokio-stream = "0.1.9"
whoami = "1.2.1"

[dev-dependencies]
env_logger = "0.9.0"
proptest = "1.0.0"
rust-embed = "6.4.0"
tempfile = "3.3.0"
tokio-test = "0.4.2"
