[package]
name = "aws-sdk-manager"
version = "0.0.6" # https://crates.io/crates/aws-sdk-manager/versions
edition = "2021"
rust-version = "1.62"
publish = true
description = "AWS SDK manager"
homepage = "https://github.com/gyuho/aws-sdk-manager"
license = "Apache-2.0"

[dependencies]
aws-config = "0.15.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-cloudformation = "0.15.0"
aws-sdk-cloudwatch = "0.15.0"
aws-sdk-cloudwatchlogs = "0.15.0"
aws-sdk-ec2 = "0.15.0"
aws-sdk-kms = "0.15.0"
aws-sdk-s3 = "0.15.0"
aws-sdk-sts = "0.15.0"
aws-smithy-types = "0.45.0"
aws-types = "0.15.0"
bs58 = "0.4.0"
byteorder = "1.4.3"
chrono = "0.4.19"
hyper = { version = "0.14.19", features = ["full"] }
hyper-tls = "0.5.0"
lazy_static = "1.4.0"
log = "0.4.17"
rand = "0.8.5"
ring = "0.16.20"
ripemd = "0.1.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
tokio-stream = "0.1.9"
url = "2.2.2"
whoami = "1.2.1"

# for "compress"
flate2 = { version = "1.0.24", optional = false }
fs_extra = { version = "1.2.0", optional = false }
path-clean = { version = "0.1.0", optional = false }
tar = { version = "0.4.38", optional = false }
walkdir = { version = "2.3.2", optional = false }
zip = { version = "0.6.2", optional = false }
zstd = { version = "0.10", optional = false }

[dev-dependencies]
env_logger = "0.9.0"
proptest = "1.0.0"
rust-embed = "6.4.0"
tempfile = "3.3.0"
tokio-test = "0.4.2"
